include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - '**/*.g.dart'

linter:
  rules:
    -prefer_const_declarations
    -prefer_const_constructors
    -avoid_print
    -use_key_in_widget_constructors
    -always_use_package_imports